version: '3'

services:
  db_postgres:
    container_name: db_boilerplate
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - ./database/boilerplate:/var/lib/postgresql/data/

  be_boilerplate:
    container_name: be_boilerplate
    build: .
    restart: always
    entrypoint: /bin/sh './scripts/be-node-dev.sh'
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - db_postgres